server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: theatre-service
          uri: lb://theatre-service
          predicates:
            - Path=/theatres/**
        - id: show-service
          uri: lb://show-service
          predicates:
            - Path=/shows/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: user-service
        url: http://localhost:9010/v3/api-docs
      - name: movie-service
        url: http://localhost:9011/v3/api-docs
      - name: theatre-service
        url: http://localhost:9012/v3/api-docs
      - name: show-service
        url: http://localhost:9013/v3/api-docs
      - name: payment-service
        url: http://localhost:9015/v3/api-docs
      - name: booking-service
        url: http://localhost:9014/v3/api-docs


